### ISSUE TITLE
Warcraft2 crash with a customized pud

### ISSUE THREAD

**Issue by jonolemon** [war2/war2edit#9]
a crash appeared after some times ... (kernel panic)
[sauvez le mage.pud.zip](https://github.com/jeanguyomarch/war2edit/files/440724/sauvez.le.mage.pud.zip)

**Comment by jonolemon** [comment]
[sauvez le mage.pud.zip](https://github.com/jeanguyomarch/war2edit/files/440737/sauvez.le.mage.pud.zip)

**Comment by jeanguyomarch** [comment]
I can observe very weird behaviours:
- the red shipyard and foundry can be built onto...
- the red tanker created by the AI is going nuts...
- after quitting the game DOSBox says "Error GDS heap corrupt" 

So I guess there is something wrong with the placed shipyard/foundry... will investigate...

**Comment by jeanguyomarch** [comment]
Mhh... ok I get it. The oil patch is misaligned.
I think that is required because water units can only move 2 cells at the time. So a fix would be to prevent creating oil patches that are on odd cells (starting at 0,0). As a temporary workaround, you can move your oil patch one cell up and one cell to the left.

**Comment by jeanguyomarch** [comment]
Turns out we needed to prevent from placing wells on even cells instead of odd.

**Comment by jonolemon** [comment]
Well done !
